CREATE DATABASE mydb
  WITH OWNER admin
  TEMPLATE template0
  TABLESPACE  pg_default
  ENCODING 'UTF8'
  LC_COLLATE 'C'
  LC_CTYPE 'C'
  CONNECTION LIMIT -1;
CREATE USER mydbuser
  WITH PASSWORD 'mydbuserpass';
GRANT ALL PRIVILEGES
  ON DATABASE mydb
  to mydbuser;
